---
title: "replicate-jose"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dGC)
library(tidyverse)
```

```{r, eval = FALSE}
data <- read_rds("~/Downloads/jhl_beta_rpkm_munged.rds")

M <- compute_residuals(data$matrix, cells = data$obs$cell, donor_vec = data$obs$donor,ncores = 6)
data$matrix <- M
data <- validate_data(data)

tictoc::tic()
testing <- corr_permute(
  data,
  n_iter =100,
  fit_models = "none",
  n_ctrl = 5, 
  n_case = 4,
  ncores=6,
)
tictoc::toc()



cond <- split(data$obs, data$obs$status)

real_diff <- corr_diff(
  data$matrix,
  cond[[1]],
  cond[[2]],
  fit_models = "blmer",
  method = "pearson",
  ncores = 6
)

permutations <- testing
mask <- mask_from_perm(P = permutations, R = real_diff, alpha = 0.05)

real_diff[mask > 0.05] <- 0


mask <- mask_from_perm(P = permutations[-12], R =permutations[[12]], alpha = 0.05)

real_diff <- permutations[[12]]
real_diff[mask > 0.05] <- 0
normalise_edges <- TRUE
if(normalise_edges) {
  real_diff <- real_diff / max(abs(real_diff))
}

dissTOM <- WGCNA::TOMdist(as.matrix(real_diff), TOMType = "signed")
hierTOM <- stats::hclust(stats::as.dist(dissTOM), method = "average")



cutoff <- c(0.974, 0.981, 0.987, 0.992, 0.992)
deep_split <- c(FALSE, FALSE, FALSE, FALSE, TRUE)
module_list <- purrr::map2(cutoff, deep_split, \(cut_off, deep) dynamicTreeCut::cutreeDynamic(hierTOM, method = "tree", minClusterSize = 30, cutHeight = cut_off, deepSplit = deep) |> WGCNA::labels2colors())


WGCNA::plotDendroAndColors(
  hierTOM,
  data.frame(module_list),
  c("Modules1", "Modules2", "Modules3", "Modules4", "Modules5"),
  dendroLabels = FALSE,
  hang = 0.03,
  addGuide = TRUE,
  guideHang = 0.05,
  main = "Hierarchical clustering",
  autoColorHeight = FALSE
)

ll <- dplyr::tibble(cluster = module_list[[1]], gene = rownames(M))
sets <- purrr::map(setdiff(unique(ll$cluster), "grey"), \(clust) dplyr::filter(ll, cluster == clust) |> dplyr::pull(gene)) |>
  purrr::set_names(setdiff(unique(ll$cluster), "grey"))



bg_ensgid <- AnnotationDbi::mapIds(org.Hs.eg.db::org.Hs.eg.db, keys = colnames(M), keytype = c("ALIAS"), column = "ENSEMBL")
gs <- readr::read_rds("inst/extdata/go-terms.rds")

all <- purrr::map(sets, \(set) {
  gsa(
    geneset=AnnotationDbi::mapIds(org.Hs.eg.db::org.Hs.eg.db, keys = set, keytype = c("ALIAS"), column = "ENSEMBL"),
    pathways = gs,
    backg = bg_ensgid,
  ) |>
    dplyr::filter(p_hyper < (0.05 / n_sets_tested))

})



```


```{r, eval = FALSE}
load("~/projects/dcgna_t2d/workflow/raw_data/hjerling_leffler/ClusteredData_20210723.RData")
```

```{r, eval=FALSE}
matrix <- DataExprGrouped_RPKM
matrix <- t(matrix)

cell_id <- as.character(TraitsWithCellType["CellID",])
status <- as.character(TraitsWithCellType["Disease",])
celltype <- as.character(TraitsWithCellType["CellType",])
donor <- as.character(TraitsWithCellType["Donor",]) |> janitor::make_clean_names(allow_dupes = TRUE) 

rownames(matrix) <- cell_id

obs <- dplyr::tibble(
  cell = cell_id,
  status = status,
  celltype = celltype,
)

var <- dplyr::tibble(gene = colnames(matrix))


data <- list(
  matrix = matrix,
  obs = obs,
  var = var
)
readr::write_rds(data, "~/projects/dcgna/workflow/t2d/hjerling-leffler_rpkm.rds")


data <- readr::read_rds("~/projects/dcgna/workflow/t2d/hjerling-leffler_rpkm.rds")

data <- validate_data(data)
data$matrix |> dim()
data$o
reduced <- prep_cluster_counts(data, "Beta", ct_column = "celltype", prop_cells = 0.3)

  all <-
    reduced$obs |>
    dplyr::filter(dataset == "jhl") |>
    dplyr::count(donor, status) |>
    dplyr::filter(n >= 20)

  reduced$obs <- dplyr::filter(reduced$obs, donor %in% all$donor)
  reduced <- validate_data(reduced)

  conditions <- split(reduced$obs,reduced$obs$status)


  real_diff <- corr_diff(
    reduced$matrix,
    conditions[[1]],
    conditions[[2]],
    fit_models = "blmer",
    method = "pearson",
    ncores = 6
  )





```





```{r,eval=FALSE}
library(Matrix)
library(WGCNA)
library(ggplot2)
library(tsne)
library(Rtsne)
library(igraph)
library(dendextend)
source("/nas/longleaf/home/josean/code/basic_functions_20211019.R")
source("/nas/longleaf/home/josean/code/plot_functions_20210629.R")
library(colorspace)
library(lme4)
library(blme)
library(performance)
library(reshape2)
library(parallel)

setwd('/nas/longleaf/home/josean/dGSNA/BetaCells/Analysis_10/')
dir<-"/nas/longleaf/home/josean/data/Diabetes/"

Disease<-readRDS(file=paste0(dir,"Disease_20210726.rds"))

samples<-readRDS(file=paste0(dir,"SampleList_rpkm_20210726.rds"))
clustersAnnotation<-readRDS(file=paste0(dir,"CellType_20210726.rds"))

NCORES<-16
MIN_CELLS<-20
#FIXED_NUMBER_CELLS<-100

print(paste0("Number of cores detected: ",detectCores()))

sa<-SelectCellCommunities(samples,clustersAnnotation,c("Beta"),min_cells = MIN_CELLS)

#sfn<-GetFixedNumberOfCells(sa,NumberOfCells = FIXED_NUMBER_CELLS)

states<-SamplesStates(sa,Disease)
states

GetNumberOfCells(samples,clustersAnnotation,c("Beta"),states,save=TRUE,filename="Ncells_betacells.rds")


genes<-GetCommonExpressedGenes(sa,samp=NULL,min_expr=2,met="NumberOfCells",min_cells=10,cell_proportion=0.3,print=TRUE,FileName="BetaCells_BackgroundGeneSet.txt")
genes

lm<-GetLinearModel(sa,sample_groups=states,genes=genes,model="blmer",normalization=TRUE)

sm<-FindSimilaritiesForNestedData(data_lm=lm,method="pearson")

saveRDS(sm,file="similarities_matrices.rds")

mask<-GetMaskFromRandomDonors(input_data=sa,sample_groups=states,
                              SimilarityDifferences=sm[["type II diabetes"]]-sm[["normal"]],
                              genes=genes,model="blmer",normalization=TRUE,replacement=FALSE,method="pearson",
                              T=512,Nctrl=5,Ncases=4,verbose=TRUE,ncores=NCORES)

saveRDS(mask,file="mask_matrix.rds")
```


